import sanitizeHtml from 'sanitize-html';

/**
 * Trusted domains for embedded iframes (e.g., YouTube, Vimeo, Calendly, Google Maps)
 */
export const TRUSTED_IFRAME_HOSTS = [
  'www.youtube.com',
  'youtube.com',
  'www.youtube-nocookie.com',
  'youtube-nocookie.com',
  'player.vimeo.com',
  'calendly.com',
  'www.google.com',
  'google.com',
  'maps.google.com',
];

/**
 * Validates whether an embed URL is on the trusted HTTPS host allowlist.
 */
export function isTrustedEmbedUrl(rawUrl: string | null | undefined): boolean {
  if (!rawUrl || typeof rawUrl !== 'string') return false;
  try {
    const parsed = new URL(rawUrl);
    return parsed.protocol === 'https:' && TRUSTED_IFRAME_HOSTS.includes(parsed.hostname.toLowerCase());
  } catch {
    return false;
  }
}

/**
 * Minimal, strict sanitize-html options matching TipTap & legacy renderer output
 */
export const SANITIZE_OPTIONS: sanitizeHtml.IOptions = {
  allowedTags: [
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    'p', 'strong', 'b', 'em', 'i', 'u', 'code', 'pre', 'blockquote',
    'ul', 'ol', 'li',
    'table', 'thead', 'tbody', 'tr', 'th', 'td',
    'a', 'img', 'figure', 'figcaption',
    'hr', 'br', 'div', 'span',
    'iframe',
  ],
  allowedAttributes: {
    a: ['href', 'title', 'target', 'rel', 'class'],
    img: ['src', 'alt', 'title', 'width', 'height', 'loading', 'class', 'style'],
    iframe: ['src', 'title', 'loading', 'allow', 'allowfullscreen', 'class', 'style'],
    table: ['class'],
    th: ['colspan', 'rowspan', 'class', 'style'],
    td: ['colspan', 'rowspan', 'class', 'style'],
    div: ['class', 'style', 'data-block', 'data-code', 'data-body'],
    span: ['class', 'style'],
    figure: ['class', 'style', 'data-block'],
    figcaption: ['class'],
    p: ['class'],
    h1: ['class'],
    h2: ['class'],
    h3: ['class'],
    h4: ['class'],
    h5: ['class'],
    h6: ['class'],
    ul: ['class'],
    ol: ['class'],
    li: ['class'],
    code: ['class'],
    pre: ['class'],
    blockquote: ['class'],
  },
  allowedSchemes: ['https', 'mailto', 'tel'],
  allowedSchemesByTag: {
    img: ['https', 'data'],
    iframe: ['https'],
  },
  allowProtocolRelative: false,
  allowedStyles: {
    '*': {
      // Strictly business-critical styles generated by the editor layout & typography
      'background-color': [/^#(0x)?[0-9a-fA-F]{3,8}$/, /^rgb\(/, /^rgba\(/],
      'color': [/^#(0x)?[0-9a-fA-F]{3,8}$/, /^rgb\(/, /^rgba\(/],
      'font-weight': [/^\d{3}$/, /^bold$/, /^normal$/],
      'width': [/^\d+(%|px|rem)$/],
      'max-width': [/^\d+(%|px|rem)$/],
      'height': [/^\d+(%|px|rem)$/, /^auto$/],
      'padding': [/^\d+(px|rem)$/],
      'gap': [/^\d+(px|rem)$/],
      'grid-template-columns': [/.+/],
      'object-position': [/^(center|top|bottom|left|right)$/],
      'opacity': [/^\d+(\.\d+)?$/],
    },
  },
  transformTags: {
    a: (tagName, attribs) => {
      // Force rel="noopener noreferrer" for any target="_blank"
      if (attribs.target === '_blank') {
        attribs.rel = 'noopener noreferrer';
      }
      return { tagName, attribs };
    },
    iframe: (tagName, attribs) => {
      // Validate iframe host against strict allowlist
      if (!attribs.src) {
        return { tagName: 'span', attribs: { class: 'hidden' } };
      }
      try {
        const url = new URL(attribs.src);
        if (url.protocol !== 'https:' || !TRUSTED_IFRAME_HOSTS.includes(url.hostname)) {
          // Reject untrusted iframes
          return { tagName: 'span', attribs: { class: 'hidden' } };
        }
      } catch {
        return { tagName: 'span', attribs: { class: 'hidden' } };
      }
      return { tagName, attribs };
    },
  },
  disallowedTagsMode: 'discard',
};

/**
 * Server-safe sanitizer for HTML derived from database or editor content
 */
export function sanitizeContentHtml(dirtyHtml: string | null | undefined): string {
  if (!dirtyHtml || typeof dirtyHtml !== 'string') {
    return '';
  }
  return sanitizeHtml(dirtyHtml, SANITIZE_OPTIONS);
}

/**
 * Escapes `<` and `>` in JSON-LD objects to prevent script-tag termination XSS
 * (e.g. `</script><script>alert(1)</script>`)
 */
export function safeJsonLd(data: unknown): string {
  return JSON.stringify(data)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e');
}
