import sanitizeHtml from 'sanitize-html';
import { TRUSTED_FRAME_HOSTS, isSafeEmbedUrl } from './url-safety';

/**
 * Minimal, strict sanitize-html options matching TipTap & legacy renderer output
 */
export const SANITIZE_OPTIONS: sanitizeHtml.IOptions = {
  allowedTags: [
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    'p', 'strong', 'b', 'em', 'i', 'u', 'code', 'pre', 'blockquote',
    'ul', 'ol', 'li',
    'table', 'thead', 'tbody', 'tr', 'th', 'td',
    'a', 'img', 'figure', 'figcaption',
    'hr', 'br', 'div', 'span',
    'iframe',
  ],
  allowedAttributes: {
    a: ['href', 'title', 'target', 'rel', 'class'],
    img: ['src', 'alt', 'title', 'width', 'height', 'loading', 'class', 'style'],
    iframe: ['src', 'title', 'loading', 'allow', 'allowfullscreen', 'class', 'style'],
    table: ['class'],
    th: ['colspan', 'rowspan', 'class', 'style'],
    td: ['colspan', 'rowspan', 'class', 'style'],
    div: ['class', 'style', 'data-block', 'data-code', 'data-body'],
    span: ['class', 'style'],
    figure: ['class', 'style', 'data-block'],
    figcaption: ['class'],
    p: ['class'],
    h1: ['class'],
    h2: ['class'],
    h3: ['class'],
    h4: ['class'],
    h5: ['class'],
    h6: ['class'],
    ul: ['class'],
    ol: ['class'],
    li: ['class'],
    code: ['class'],
    pre: ['class'],
    blockquote: ['class'],
  },
  allowedSchemes: ['https', 'mailto', 'tel'],
  allowedSchemesByTag: {
    img: ['https', 'data'],
    iframe: ['https'],
  },
  allowProtocolRelative: false,
  allowedStyles: {
    '*': {
      // Strictly business-critical styles generated by the editor layout & typography
      'background-color': [/^#(0x)?[0-9a-fA-F]{3,8}$/, /^rgb\(/, /^rgba\(/],
      'color': [/^#(0x)?[0-9a-fA-F]{3,8}$/, /^rgb\(/, /^rgba\(/],
      'font-weight': [/^\d{3}$/, /^bold$/, /^normal$/],
      'width': [/^\d+(%|px|rem)$/],
      'max-width': [/^\d+(%|px|rem)$/],
      'height': [/^\d+(%|px|rem)$/, /^auto$/],
      'padding': [/^\d+(px|rem)$/],
      'gap': [/^\d+(px|rem)$/],
      'grid-template-columns': [/.+/],
      'object-position': [/^(center|top|bottom|left|right)$/],
      'opacity': [/^\d+(\.\d+)?$/],
    },
  },
  transformTags: {
    a: (tagName, attribs) => {
      if (attribs.target === '_blank') {
        attribs.rel = 'noopener noreferrer';
      }
      return { tagName, attribs };
    },
    iframe: (tagName, attribs) => {
      if (!attribs.src || !isSafeEmbedUrl(attribs.src)) {
        return { tagName: 'span', attribs: { class: 'hidden' } };
      }
      return { tagName, attribs };
    },
  },
  disallowedTagsMode: 'discard',
};

/**
 * Server-safe sanitizer for HTML derived from database or editor content
 */
export function sanitizeContentHtml(dirtyHtml: string | null | undefined): string {
  if (!dirtyHtml || typeof dirtyHtml !== 'string') {
    return '';
  }
  return sanitizeHtml(dirtyHtml, SANITIZE_OPTIONS);
}
